keyboard.bindings = [
    { key = "Left", mods = "Command", chars = "\u001bOH", mode = "AppCursor" },
    { key = "Right", mods = "Command", chars = "\u001bOF", mode = "AppCursor" },

    { key = "Left", mods = "Alt", chars = "\u001bb" },
    { key = "Right", mods = "Alt", chars = "\u001bf" },

    { key = "Back", mods = "Super", chars = "\u0015" },

    { key = "K", mods = "Command", action = "ClearHistory" },
]
