[font]
offset.y = 1
offset.x = -1
normal = { family = "SpaceMono Nerd Font", style = "Regular" }
bold = { family = "SpaceMono Nerd Font", style = "Bold" }
bold_italic = { family = "SpaceMono Nerd Font", style = "Bold Italic" }
italic = { family = "SpaceMono Nerd Font", style = "Italic" }
